# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ml-book',
                'doc_host': 'https://acciochris.github.io',
                'git_url': 'https://github.com/acciochris/ml-book',
                'lib_path': 'ml_book'},
  'syms': { 'ml_book.core': {'ml_book.core.foo': ('core.html#foo', 'ml_book/core.py')},
            'ml_book.notes': {'ml_book.notes.foo': ('notes.html#foo', 'ml_book/notes.py')}}}
